### ISSUE TITLE
OpenSSL not found

### ISSUE THREAD

**Issue by cooperkernan** [rustyrussell/bitcoin-iterate#11]
cc -O3 -flto -ggdb -I ccan/ -Wall   -c -o iterate.o iterate.c
In file included from iterate.c:22:
In file included from ./parse.h:3:
./types.h:4:10: fatal error: 'openssl/sha.h' file not found
#include <openssl/sha.h>
         ^~~~~~~~~~~~~~~
1 error generated.
make: *** [iterate.o] Error 1

**Comment by cooperkernan** [comment]
Could be similar to https://github.com/lastpass/lastpass-cli/issues/133?

**Comment by rustyrussell** [comment]
You need the openssl libraries installed.  On Ubuntu and Debian, this means `libssl-dev`.
