### ISSUE TITLE
Is it possible to only get the first output of each coinbase transaction?

### ISSUE THREAD

**Issue by in3rsha** [rustyrussell/bitcoin-iterate#14]
Hello there,

First of all, thank you for the excellent tool.

**Is it possible to get the first output from the coinbase transaction only from each block?**

I can get the input for each coinbase transaction with this command:

```
# %iB: input UTXO block number (0 for coinbase)
bitcoin-iterate -q --input=%iB,%is | grep "^0,"
```

However, I'm not sure how to get the **first output** from the coinbase transaction only, as this command returns _every_ first output for each transaction in the block:

```
# %oN: output number
bitcoin-iterate -q --output=%oN,%os | grep "^0,"
```

I'm trying to identify the miner behind each block. I can mostly do this looking at the `scriptSig` of the input in the coinbase transaction, but it seems that some miners identify themselves by the address they use to claim the block reward, which can be found in the `scriptPubKey` on the first output in the coinbase transaction.

I'm not sure if getting only the coinbase transaction's first output is possible, but I thought it would be best to ask.

-----

**EDIT:** I'm guessing one solution would be to the hex of every coinbase transaction, then decode each one with `bitcoin-cli` and filter out the first output's address with `jq`:

```
bitcoin-iterate -q --transaction=%tN,%tX | grep "^0," | cut -d "," -f 2
# next: bitcoin-cli decoderawtransaction
# next: jq
```

**Comment by rustyrussell** [comment]
grep can do this filtering: `%tN,%oN,%os | grep ^0,0,`
