### ISSUE TITLE
Is it safe to launch while bitcoind is running?

### ISSUE THREAD

**Issue by RCasatta** [rustyrussell/bitcoin-iterate#8]
The question regard only the point of view of the bitcoind node, I don't care if bitcoin-iterate in some case crash or creates not perfect statistics because can't read a block file modified by the node.

**Comment by rustyrussell** [comment]
Riccardo Casatta <notifications@github.com> writes:
> The question regard only the point of view of the bitcoind node, I don't care if bitcoin-iterate in some case crash or creates not perfect statistics because can't read a block file modified by the node.

Yes, I do it all the time.

Cheers,
Rusty.

**Comment by RCasatta** [comment]
Thanks!
